### ISSUE TITLE
Update Developer Guide with Implementation Details

### ISSUE THREAD

**Issue by prokarius** [CS2103-AY1819S1-F10-2/main#93]
Describe the implementation of current/ future enhancement(s)

Progress:
- [x] @prokarius 
- [x] @wn96 
- [x] @xantho09 
- [x] @Kelly9373 
- [x] @FongYuan

**Comment by FongYuan** [comment]
"Each of you were supposed to add about 1 page of content (including some UML diagrams) to the Developer Guide by v1.2, so that we can give you feedback on your DG-writing and UML-modelling skills. If you did not do that, please do that soon or else you lose this opportunity to recieve feedback. Once all team members have done that, please post a comment in your team PR ([here](https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/54)) requesting the tutor to review new additions to the DG."
